### ISSUE TITLE
Why does using handlebars-helpers require grunt?

### ISSUE THREAD

**Issue by podviaznikov** [assemble/handlebars-helpers#176] opened 2015-01-13 20:27 UTC
I see `grunt` is required here https://github.com/assemble/handlebars-helpers/blob/84dcfdd2b42c54ed71ded34b68941466286ead2b/lib/helpers/helpers-files.js#L10 but never used in that file.

Same goes for https://github.com/assemble/handlebars-helpers/blob/84dcfdd2b42c54ed71ded34b68941466286ead2b/lib/helper-lib.js#L21.

Utils use `grunt`, but they never used in `helper-lib.js`.

Can those two `require` be removed?

**Comment by jonschlinkert** [comment] 2015-01-13 22:56
This is probably the 5th or 6th dupe of this issue. please search first.

**Closed by jonschlinkert** 2015-01-13 22:56 UTC

**Comment by podviaznikov** [comment] 2015-01-13 22:59
I found issues about moving `grunt` from `devDependencies` to `dependencies`.

My questions was about why `grunt` is actually required for the `helpers`? I found few `require` statements that were never used.

**Comment by pburtchaell** [comment] 2015-01-15 04:42
If you [search for the Grunt keyword in this repo](https://github.com/assemble/handlebars-helpers/search?q=grunt&type=Issues&utf8=%E2%9C%93), I think you will find the answer to your question. There are issues related to this question and you can see that some of the utils depend on Grunt.
