### ISSUE TITLE
Warning: Missing helper: 'is' Use --force to continue.

### ISSUE THREAD

**Issue by ANTON072** [assemble/handlebars-helpers#184] opened 2015-04-09 08:21 UTC
The helper 'is' dose not work now. 

```
<li><a href="#"{{#is active "fuga"}} class="rc-h-active"{{/is}}>hogehoge</a></li>
```

assemble version is `"assemble": "^0.4.42"`.

It was working to this before. Why not working?

**Comment by ijdickinson** [comment] 2015-04-20 12:13
I've just been bitten by the same thing. In my case, I cloned a repo that is working, and after running `npm install` on the same `package.json`, I get the "Missing helper: 'is'" message when I run `grunt assemble`. The npm version is the same in both cases, since it's running on the same machine. 

It seems likely that it's a dependency issue. After some experimentation, I found that pinning `assemble-handlebars` to version 0.2.3 and `handlebars-helpers` to 0.5.1 in `package.json`, nuking node_modules and `npm install`ing again seems to work, which gets me out of my current hole but doesn't explain what the cause is.

I'm happy to do any other digging necessary to get to the bottom of this, if  you have suggestions!

**Comment by doowb** [comment] 2016-06-08 19:29
Closing due to the refactor and that [{{is}}](https://github.com/assemble/handlebars-helpers/blob/master/lib/comparison.js#L323) is currently in this repo. Also, when using assemble with grunt, you should use [grunt-assemble](https://github.com/assemble/grunt-assemble) now.

**Closed by doowb** 2016-06-08 19:29 UTC
